--- #YAML:1.0
name:               Class-Fields
version:            0.204
abstract:           Inspect the fields of a class.
author:
    - Michael G Schwern <schwern@pobox.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    base:          2
    Carp:          0
    Carp::Assert:  0
    constant:      0
    Test::More:    0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_06
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
