--- #YAML:1.0
name:                Class-Fields
version:             0.202
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.34
distribution_type:   module
requires:     
    base:                          2
    Carp:                          0
    Carp::Assert:                  0
    constant:                      0
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
